import type { NativeWorkMode, WorkModeTone } from "../types.ts";

/**
 * A Codex work mode: what Shell shows (`label`, `tone`), the id it remembers (`approval:sandbox`), and the
 * two protocol values it sends — `approvalPolicy` and `sandbox`, both exactly as the app-server names
 * them (`thread/start` takes `sandbox` as is; `turn/start` takes it as a `sandboxPolicy`, see `sandboxPolicyFor`).
 */
export interface CodexWorkMode extends NativeWorkMode {
  approvalPolicy: string;
  sandbox: string;
}

/**
 * Codex's `SandboxMode` values (`v2/SandboxMode.ts` of the protocol generated by `codex app-server
 * generate-ts`, codex-cli 0.159.0) and the `type` each one takes inside a `turn/start` `sandboxPolicy`
 * (`v2/SandboxPolicy.ts`). A sandbox Codex reports that is not here cannot be turned into a valid policy,
 * so it is never offered.
 */
const SANDBOX_POLICY_TYPE: Record<string, string> = {
  "read-only": "readOnly",
  "workspace-write": "workspaceWrite",
  "danger-full-access": "dangerFullAccess",
};

/** Codex's plain `AskForApproval` strings (`v2/AskForApproval.ts`); its object form `{ granular }` is not a mode Codex's own picker offers. */
const APPROVAL_POLICIES = ["untrusted", "on-request", "never"];

/**
 * The three permission presets Codex's own picker shows, with the names it shows and the protocol values
 * each one stands for. The names are Codex's (strings of codex-cli 0.159.0's picker: «Read Only»,
 * «Default», «Full Access»); the protocol has no request that returns them, so they live here — but every
 * value is the protocol's, never a retired one. Codex's restrictions (`configRequirements/read`) narrow this list.
 */
const PRESETS: { name: string; approvalPolicy: string; sandbox: string; tone: WorkModeTone }[] = [
  { name: "Read Only", approvalPolicy: "on-request", sandbox: "read-only", tone: "readOnly" },
  { name: "Default", approvalPolicy: "on-request", sandbox: "workspace-write", tone: "manual" },
  { name: "Full Access", approvalPolicy: "never", sandbox: "danger-full-access", tone: "danger" },
];

/** Keeps only plain strings from a list Codex reported; `null`/absent means «no restriction». Object forms (`{ granular }`) are dropped. */
function allowedStrings(value: unknown): string[] | null {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : null;
}

function toneFor(sandbox: string): WorkModeTone {
  return sandbox === "danger-full-access" ? "danger" : sandbox === "read-only" ? "readOnly" : "manual";
}

/**
 * The modes Shell offers for Codex, from what Codex allows. `requirements` is the `requirements` field of
 * `configRequirements/read` (`null`/absent when nothing restricts, or when the call is not available):
 * then all three presets are offered. When Codex restricts the approval policies and/or sandboxes, only the
 * presets it still permits are offered; and if the restriction excludes every preset, exactly what Codex
 * allows is offered instead, named with the protocol's own values.
 */
export function buildCodexWorkModes(requirements: { allowedApprovalPolicies?: unknown; allowedSandboxModes?: unknown } | null | undefined): CodexWorkMode[] {
  const policies = allowedStrings(requirements?.allowedApprovalPolicies);
  const sandboxes = allowedStrings(requirements?.allowedSandboxModes)?.filter(sandbox => Object.hasOwn(SANDBOX_POLICY_TYPE, sandbox)) ?? null;
  const allowed = (approvalPolicy: string, sandbox: string) => (!policies || policies.includes(approvalPolicy)) && (!sandboxes || sandboxes.includes(sandbox));
  const make = (label: string, approvalPolicy: string, sandbox: string, tone: WorkModeTone): CodexWorkMode => ({ id: `${approvalPolicy}:${sandbox}`, label, tone, approvalPolicy, sandbox });
  const presets = PRESETS.filter(preset => allowed(preset.approvalPolicy, preset.sandbox));
  if (presets.length) return presets.map(preset => make(preset.name, preset.approvalPolicy, preset.sandbox, preset.tone));
  return (policies ?? APPROVAL_POLICIES).flatMap(approvalPolicy =>
    (sandboxes ?? Object.keys(SANDBOX_POLICY_TYPE)).map(sandbox => make(`${approvalPolicy} · ${sandbox}`, approvalPolicy, sandbox, toneFor(sandbox))));
}

/** The `sandboxPolicy` a `turn/start` takes for a `SandboxMode` value, e.g. `"read-only"` → `{ type: "readOnly" }`. */
export function sandboxPolicyFor(sandbox: string): { type: string } {
  return { type: SANDBOX_POLICY_TYPE[sandbox]! };
}
